# Generated by Django 4.0.4 on 2022-09-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
